image: Ubuntu1804

environment:
  matrix:
    - MINGW_VERSION: i686
    - MINGW_VERSION: x86_64

matrix:
  fast_finish: true

clone_depth: 1

build: off
test: off

init:
  - sudo apt-get -y install git cmake gcc-mingw-w64 g++-mingw-w64 autoconf libtool pkg-config libglib2.0-dev gnome-common gtk-doc-tools libgtk2.0-dev ocaml ocamlbuild fig2dev texinfo

build_script:
  - ./build.sh ${MINGW_VERSION}

